### PR TITLE
RELEASE: v0.10.0

### PR DESCRIPTION
**Pull request by jkremser**
:shipit: 🚢 🚀 
Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>

### CODE REVIEW

**Comment by jkremser** [comment]
@ytsarev created https://github.com/k8gb-io/k8gb/issues/974 for the test failure and re-run it

**Comment by ytsarev** [comment]
@jkremser release Gods are not on our side today https://github.com/k8gb-io/k8gb/actions/runs/3273083161/jobs/5384868194 , different stuff now

**Review by kuritka — APPROVED** [review]

**Comment by ytsarev** [comment]
@jkremser @kuritka if we ignore the result of CI can we please properly discuss and document it?

**Comment by jkremser** [comment]
I didn't ignore, it was green when merging... re-run helped, but I agree we have a heisenbug there. There is an issue created for it.

**Comment by ytsarev** [comment]
@jkremser got it 👍

**Pull request merged**
