### PR TITLE
Add GitHub buttons to k8gb.io header

### PR DESCRIPTION
**Pull request by ytsarev**
* Add https://ghbtns.com/ powered buttons
* Remove dead tar.gz downloading code

Signed-off-by: Yury Tsarev <yury.tsarev@absa.africa>

### CODE REVIEW

**Comment by ytsarev** [comment]
Looks like
image

**Comment by somaritane** [comment]
Can we try to move these to the footer? Or maybe we need to restructure and slim down the template a bit.
I'm just afraid that by adding these we already eating out half of the screen estate, leaving little place for the actual content.

The same goes about the mobile view, (probably it needs some burger button for navigation instead of vertical buttons):

**Comment by ytsarev** [comment]
@somaritane moving to footer defeats the obvious goal of the star gathering ;)

**Review by kuritka — APPROVED** [review]
👍

**Review by somaritane — APPROVED** [review]

**Pull request merged**
