### PR TITLE
Fix chart repo url after org move

### PR DESCRIPTION
**Pull request by k0da**
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

### CODE REVIEW

**Comment by k0da** [comment]
@ytsarev coredns-helm wasn't moved

**Comment by ytsarev** [comment]
@k0da should it be moved then?

**Comment by k0da** [comment]
Not sure we should do this during release :D

**Comment by ytsarev** [comment]
fair enough :)

**Review by ytsarev — APPROVED** [review]

**Pull request merged**
