### PR TITLE
Put OLM bundle under release publish

### PR DESCRIPTION
**Pull request by k0da**
Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

### CODE REVIEW

**Review by somaritane — CHANGES_REQUESTED** [review]
@k0da it probably makes sense to rename WF file to `publish_artifacts.yaml`, and WF to `Publish Artifacts` to reflect the WF contents,  as OLM bundle is not technically a helm chart.

**Comment by k0da** [comment]
> @k0da it probably makes sense to rename WF file from `helm_publish` to `publish_artifacts.yaml`, and WF to `Publish Artifacts` to reflect the WF contents, as OLM bundle is not technically a helm chart.

Arguable, it just triggers other workflow which uses Helm as source for manifests. From my POV it still quite pure helm task.

**Review by somaritane — CHANGES_REQUESTED** [review]
> > Arguable, it just triggers other workflow which uses Helm as source for manifests. From my POV it still quite pure helm task. 

@k0da what about changing the event type in `olm_pr.yaml` job from:
```
on:
  workflow_dispatch:
```
to
```
on:
  release:
    types:
      - published
```
This way it is triggered by release event in parallel with `help_publish`.

**Comment by jkremser** [comment]
> what about changing the event type in olm_pr.yaml job from

we would lose a way to hot-fix existing bundle by manually triggering the action. I had to that for instance for [this issue](https://github.com/k8gb-io/k8gb/issues/757) using [this pipeline](https://github.com/k8gb-io/k8gb/runs/4253469608?check_suite_focus=true#step:8:8) (resulting [pr](https://github.com/k8s-operatorhub/community-operators/pull/420/files))

**Review by jkremser — APPROVED** [review]

**Review by somaritane — APPROVED** [review]

**Comment by k0da** [comment]
> > > Arguable, it just triggers other workflow which uses Helm as source for manifests. From my POV it still quite pure helm task.
> 
> @k0da what about changing the event type in `olm_pr.yaml` job from:
> 
> ```
> on:
>   workflow_dispatch:
> ```
> 
> to
> 
> ```
> on:
>   release:
>     types:
>       - published
> ```
> 
> This way it is triggered by release event in parallel with `help_publish`.

Making it separate would release it in parallel, I think we still want to smoke test helm itself and only after use its artifacts to build OLM

**Pull request merged**
