### PR TITLE
OpenTelemetry for k8gb

### PR DESCRIPTION
**Pull request by jkremser**
Open~Tracing~Telemetry stuff 4 k8gb

- by default, it is "noop"
- iff enabled (`tracing.enabled`):
  * helm chart deploys otel collector as a sidecar container on k8gb pod
  * iff enabled (`tracing.deployJaeger`), it deploys also Jaeger and configure the otel collector to feed it with traces
  * if enabled, collect and send following traces: `Reconcile`, `gslbDNSEndpoint`, `SaveDNSEndpoint`, `CreateZoneDelegationForExternalDNS`, `finalize`
- docs

Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
Wow, it looks seriously dope :) I would appreciate the demo on next community meeting :)

**Comment by jkremser** [comment]
@ytsarev I've already [did](https://www.youtube.com/watch?v=lV82xwA9i2c&t=300s&ab_channel=K8GB)

**Review by kuritka — APPROVED** [review]
perfect.

**Review by ytsarev — APPROVED** [review]
Really dope

**Pull request merged**
