### PR TITLE
add .status.hosts for better ux

### PR DESCRIPTION
**Pull request by jkremser**
Issue: https://github.com/k8gb-io/k8gb/issues/922

```bash
λ k get gslb -A
NAMESPACE   NAME                 STRATEGY     GEOTAG
test-gslb   test-gslb            roundRobin   us
test-gslb   test-gslb-failover   failover     us

λ k get gslb -A -owide
NAMESPACE   NAME                 STRATEGY     GEOTAG   HOSTS
test-gslb   test-gslb            roundRobin   us       notfound.cloud.example.com, unhealthy.cloud.example.com, roundrobin.cloud.example.com
test-gslb   test-gslb-failover   failover     us       failover.cloud.example.com
```

### CODE REVIEW

**Review by kuritka — APPROVED** [review]
lgtm

**Review by k0da — APPROVED** [review]
Nice! 👍

**Review by somaritane — APPROVED** [review]
What an eye 🍬 @jkremser ! LGTM 👍

**Comment by jkremser** [comment]
@somaritane :question: "N" 👁️ 🍬 :)

Folks, could you pls "ptal" once again, I had some issue in test (impl was fine and is still the same)

**Review by k0da — APPROVED** [review]

**Pull request merged**
