### PR TITLE
Fix local playground setup

### PR DESCRIPTION
**Pull request by k0da**
Don't create service and don't point publish service to it. Istead use
node IPs as Ingress address

Signed-off-by: Dinar Valeev <dinar.valeev@absa.africa>

### CODE REVIEW

**Comment by k0da** [comment]
fixes https://github.com/k8gb-io/k8gb/issues/528

**Review by ytsarev — APPROVED** [review]
Good to merge assuming we create additional Issue to cover the problematic e2e scenario with terratest.

@kuritka do you agree to handle it separately assuming that `make test-round-robin` is green now?

**Review by kuritka — APPROVED** [review]

**Comment by kuritka** [comment]
@ytsarev, @k0da  agreed

**Comment by ytsarev** [comment]
@k0da sorry if I missed it, was the issue for terratest extension created before the merge?

**Comment by k0da** [comment]
@ytsarev just opened [one](https://github.com/k8gb-io/k8gb/issues/533)

**Comment by ytsarev** [comment]
@k0da thank you 👍

**Pull request merged**
