### PR TITLE
Make make colorful

### PR DESCRIPTION
**Pull request by jkremser**
what:
`s/@echo/@echo -e/g` in Makefile

why:

the `SHELL := bash` on line 36 is causing this:

```
make deploy-full-local-setup
\n\033[0;33mCreating 2 k8s clusters\033[0m
/Library/Developer/CommandLineTools/usr/bin/make create-local-cluster CLUSTER_NAME=edge-dns
\n\033[0;33mCreate local cluster \033[1;36medge-dns \033[0m
k3d cluster create -c k3d/edge-dns.yaml
INFO[0000] Using config file k3d/edge-dns.yaml (k3d.io/v1alpha3#simple)
INFO[0000] Prep: Network
..
```

i.e. echo doesn't interpret the escape characters for colors, nor the new lines. Colors can be fixed [like this](https://github.com/upbound/build/blob/bd63a4167ae20a71788537217b022fced8f2f854/makelib/common.mk#L30), but new lines (`\n`) require the `echo -e ..` (which also fixes the colors)

after:
Screenshot 2022-01-11 at 16 41 26

Signed-off-by: Jirka Kremser <jiri.kremser@gmail.com>

### CODE REVIEW

**Review by somaritane — APPROVED** [review]
LGTM 👍

**Comment by kuritka** [comment]
@jkremser  would there be any advantages/disadvantages to using `SHELL := /bin/sh` instead of the `-e` argument ?

**Comment by jkremser** [comment]
@kuritka  `SHELL := /bin/sh` would ran into the issue that on Ubuntu this points to the Dash implementation.. 

```
❯ docker run -ti --rm --entrypoint="" ubuntu ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jul 18  2019 /bin/sh -> dash
```

**Review by kuritka — APPROVED** [review]
@jkremser , Thank you for the explanation, lgtm

**Pull request merged**
