### PR TITLE
fix: externaldns.interval not being respect

### LINKED ISSUE #1676: externaldns.interval not being respect
We have noticed an instance of incorrect helming in one of your Kubernetes configuration files. Hardcoded or default configuration values in the template are considered anti-pattern and configurable values in the values.yaml file are not being respect, resulting in user-provided configurations never being applied. Additionally, we provide anecdotal evidence from [trivy-operator#729](https://github.com/aquasecurity/trivy-operator/issues/729) regarding the incorrect helming defect.

[externaldns.interval](https://github.com/k8gb-io/k8gb/blob/bd9f599ae2e1aa57e97ac721836e024c54a25b44/chart/k8gb/values.yaml#L72) does not take affect when change it to other values. This is because missing implementation for this value in external-dns/external-dns.yaml file:

https://github.com/k8gb-io/k8gb/blob/bd9f599ae2e1aa57e97ac721836e024c54a25b44/chart/k8gb/templates/external-dns/external-dns.yaml#L23

## Expected Behavior
Change externaldns.interval to other value can take effect

## Actual Behavior
Only default value '1m' take effect

### PR DESCRIPTION
**Pull request by zyue110026**
fix #1676 

respect externaldns.interval

### CODE REVIEW

**Comment by ytsarev** [comment]
@zyue110026 thanks a lot for the catch! Could you please rebase the PR with the `master` branch?  we had a regression in our test pipelines that was fixed after the merge of https://github.com/k8gb-io/k8gb/pull/1674

**Comment by ytsarev** [comment]
Made short investigation, this regression happened a while ago in https://github.com/k8gb-io/k8gb/pull/292/files#diff-c5b1eb253f3b95c48e2f9203764d56752b157636d69930e79e5e7e27a59567d0L76 . Thanks again for bringing it up 👍

**Comment by zyue110026** [comment]
@ytsarev I rebased the pr with the master branch.

**Review by ytsarev — APPROVED** [review]
Thanks a lot for the catch and the contribution!

**Pull request merged**
